Repository Extum/flarum-ext-material, pull requests merged in 2018-08, with the labels that each got.

#131 Sidebar and Icon Fixes
  resources/less/app.less
Labels: browser: chrome, bug, priority: high

#135 Nathans fixes
  resources/less/app.less
Labels: bug, icons

#146 Add CSS & JS through head strings, not through other JS
  js/admin/dist/extension.js
  js/admin/src/main.js
  js/forum/dist/extension.js
  js/forum/src/main.js
  src/Listeners/AddClientAssets.php
Labels: enhancement
