Repository Extum/flarum-ext-material, pull requests merged in 2018-07, with the labels that each got.

#1 Material Switches
  material.css
Labels: component addition, component: switch, enhancement

#2 Renaming of .Checkbox to .Checkbox-display
  material.css
Labels: bug, component: switch

#4 [wip] Fixes for alignement issues
  material.css
Labels: bug, component: button

#16 Cleanup
  material.css
Labels: cleanup

#27 Fixing issue #18
  material.css
Labels: bug, element: table, good first issue, priority: medium, status: confirmed

#25 Multiple Fixes
  material.css
Labels: bug, component: button, component: card, component: switch, element: sidebar, element: table, priority: high, status: confirmed

#32 Cleanup #2
  material.css
Labels: cleanup, priority: low

#34 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement, priority: low, repo related

#35 Update pull request templates
  PULL_REQUEST_TEMPLATE.md
Labels: enhancement, priority: low, repo related

#52 Fixes App Bar Shadow
  material.css
Labels: bug, priority: high

#56 [Mobile] Sidebar profile button fix
  material.css
Labels: priority: low

#54 Addition of border radius to the reply box
  material.css
Labels: priority: low

#55 [Mobile] Sidebar notifications button fix
  material.css
Labels: priority: low

#58 [Mobile] Fix for profile selector menu
  material.css
Labels: bug, priority: high

#62 Material Icons
  material.css
Labels: enhancement, font awesome, icons, material icons, materialization, priority: high

#68 Fix for the square loader issue on notification settings
  material.css
Labels: bug, element: table, priority: medium, status: needs verification

#75 Fix for Admin/Permissions page
  material.less
Labels: bug, priority: medium

#80 Fixes Minimize Button (Mobile and Desktop)
  material.less
Labels: priority: medium

#83 Fixes Discussion Buttons
  material.less
Labels: priority: medium

#81 Fixes Login Button Vertical Alignment
  material.less
Labels: priority: medium

#82 Fixes Check and Refresh Button
  material.less
Labels: icons

#79 Conversion to extension
  .gitignore
  LICENSE.md
  bootstrap.php
  composer.json
  js/admin/Gulpfile.js
  js/admin/dist/extension.js
  js/admin/package.json
  js/admin/src/main.js
  js/forum/Gulpfile.js
  js/forum/dist/extension.js
  js/forum/package.json
  js/forum/src/main.js
  resources/less/admin.less
  resources/less/app.less
  resources/locale/en.yml
  src/Listeners/AddClientAssets.php
Labels: enhancement, priority: high, status: confirmed

#86 Cleanup
  resources/less/app.less
Labels: cleanup, priority: low

#101 Fix for admin icons and styles
  js/admin/src/main.js
  resources/less/admin.less
Labels: bug, priority: high

#100 Fixes Tag Style
  material.less
Labels: priority: low

#99 Fixes Permission Badge Alignment
  material.less
Labels: priority: low

#102 Fix for tag dropdown
  resources/less/app.less
Labels: priority: low

#111 Material Switch Enhancements
  resources/less/app.less
Labels: enhancement, priority: low

#112 Elevation decrease
  resources/less/app.less
Labels: bug, enhancement, materialization, priority: high

#113 Extension list materialization
  resources/less/app.less
Labels: enhancement, materialization, priority: high

#114 Material icon additions & cleanup
  resources/less/app.less
Labels: cleanup, enhancement, icons, priority: high
